services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_HOST: localhost
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  # redis 8
  redis:
    image: redis:8
    ports:
      - 6379:6379
  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data
volumes:
  pgdata:
  redis-insight: