import { AppSidebar } from "@/components/app-sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import "@/styles/globals.css";
import { auth } from '@/server/auth';

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { permanentRedirect } from "next/navigation";
import { ThemeProvider } from "@/components/theme-provider"

export const metadata: Metadata = {
  title: "Manager",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth();
  if (!session) {
    permanentRedirect("/api/auth/signin");
  }
  return (
    <html lang="en" className={`${GeistSans.variable}`} suppressHydrationWarning>
      <body>
        <ThemeProvider 
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
          <SidebarProvider>
            <AppSidebar session={session}/>
            {children}
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
